pipeline {
    agent any

    /* This tells Jenkins to automatically pull and setup NodeJS version 18 */
    tools {
        nodejs 'node18' // Make sure this matches your Jenkins global tool name (usually node, node18, or NodeJS)
    }

    environment {
        DOCKER_IMAGE = 'hotel-booking-frontend'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code from GitHub...'
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing npm packages...'
                /* We run directly in the root directory now */
                sh 'npm install'
            }
        }

        stage('Build Frontend') {
            steps {
                echo 'Building React application...'
                sh 'npm run build'
            }
        }

        stage('Docker Build & Package') {
            steps {
                echo 'Building Docker container image...'
                sh "docker build -t ${DOCKER_IMAGE}:latest ."
            }
        }
    }
}